#> This is the configuration file of TrainCarts
#> In here you can tweak TrainCarts to what you want
#> For more information, you can visit the following websites:
#> http://www.minecraftwiki.net/wiki/Bukkit/TrainCarts
#> http://forums.bukkit.org/threads/traincarts.29491/

# Settings for normally-aligned (straight) carts
normal:
  # The distance between two carts in a train
  cartDistanceGap: 0.5
  # The factor at which this distance is kept
  cartDistanceForcer: 0.1
  cartDistanceForcerConstant: 0.0

# The maximum allowed cart distance, after this distance the carts break apart
maxCartDistance: 4.0

# Whether or not the combined carts (powered/storage minecarts) break up into two items
breakCombinedCarts: false

# A performance boost to give to powered minecarts (0 = normal speed)
poweredCartBoost: 0.1

# The boosting factor of powered rails (default = 0.06)
poweredRailBoost: 0.06

# The maximum velocity (blocks/tick) a minecart can possibly have set
maxVelocity: 5.0

# The multiplier used to slow down minecarts
# Normal is the default, slow is when the minecart is meant to slow down.
slowDownMultiplier:
  normal: 0.997
  slow: 0.96

# The maximum allowed ejection distance for eject signs
maxEjectDistance: 10.0

# The amount of velocity stations give when launching trains
launchForce: 10.0

# Settings used when carts collide with entities
collision:
  # If train owners are ignored
  ignoreOwners: false
  # If global train owners are ignored
  ignoreGlobalOwners: false
  # The amount of force at which minecarts push away others
  pushAwayForce: 0.2

# Whether or not all minecarts spawned on the server turn into TrainCarts' Minecarts
# Note that the TrainCart placement permission is then no longer active
allMinecartsAreTrainCarts: false

# Whether or not powered minecarts obtain their coal from attached storage minecarts
useCoalFromStorageCart: false

# Whether or not the player that places a minecart is set owner
setOwnerOnPlacement: true

# Whether or not a hissing sound is made when trains stop at a station
playSoundAtStation: true

# What style of launching to use in stations and launcher sign systems by default. Possible values:
# - 'linear': gradually switches from one motion speed to another at a linear rate
# - 'bezier': uses a bezier curve (ease in-out), resulting in slower changes in motion at start/end of launch
launchFunction: bezier

# Whether or not chunks are only kept loaded when the train is moving
keepChunksLoadedOnlyWhenMoving: false

# Whether to enable or cancel collisions with blocks above minecarts
# Some constructions depend on these block collisions to block minecarts
# If these collisions are unwanted, they can be turned off here
enableCeilingBlockCollision: true

# Advanced: Whether trains use a different way of server->client synchronization
# With this enabled, trains are expected to move smoother with less bumping
# With this disabled, no smoothing is applied. Only disable it if it causes problems/incompatibility
useNetworkSynchronizer: true

# Enable or disable seeing yourself in third-person on vertical rails
# Turning this off only causes this mode to activate when going upside-down
enableSeatThirdPersonView: true

# The maximum length a detector region (between two detectors) can be
maxDetectorLength: 2000

# The maximum amount of minecart items that can be stacked in one item
maxMinecartStackSize: 64

# The maximum radius chest/furnace sign systems look for the needed blocks
maxTransferRadius: 5

# The default radius chest/furnace sign systems look for the needed blocks
defaultTransferRadius: 2

# Whether or not empty minecarts slow down faster than occupied minecarts
slowDownEmptyCarts: false

# Whether storage minecarts get fuel when launching from stations
refillAtStations: true

# When set to true, players will be able to break minecarts with a single slap

# No item drops are spawned for minecarts destroyed this way. Minecart contents ARE dropped.
# They can still select minecarts by crouching and then slapping the minecart

# When set to false, players will never instantly destroy minecarts and they will have to break it as if in survival.
instantCreativeDestroy: true

# Whether minecarts are allowed to have a 90-degree pitch angle when going up vertical rails
# When disabled, minecarts will keep a 0-degree pitch angle instead
allowVerticalPitch: true

# Whether upside-down rail functionality is enabled on the server
# When disabled, minecarts can not be rotated upside-down
allowUpsideDownRails: true

# Before TrainCarts v1.12.1-v2 vertical rail gravity was kind of awful
# It took a lot more speed to get up a vertical rail compared to sloped rails
# This was fixed. If you depend on this legacy behavior, change this option to True
legacyVerticalGravity: false

# Before TrainCarts v1.12.2-v1 speed limiting was done on each individual axis
# This had a big impact on air physics, because it never made a good ellipse fall
# This was changed to preserving the motion vector direction when doing speed limiting
# Slight changes may have occurred in curves, slopes and through-air physics
# To restore the old limiting system, set this option to True
legacySpeedLimiting: false

# Whether players (with build permissions) can edit existing rails by right-clicking on them
allowRailEditing: true

# What velocity to set when a player tries to manually move a train (by damaging it)
manualMovementSpeed: 12.0

# The currency Ticket signs will display in messages, %value% represents the displayed value
currencyFormat: '%value% Dollars'

# Whether trains can be teleported to the nether (or back) when rails are laid close to the portals
allowNetherTeleport: true

# The delay (in ticks) between ejecting and re-entering by collision (e.g. mobs auto-entering carts)
collisionReEnterDelay: 100
# Whether powered activator rails eject players inside Minecarts (Vanilla)
# If activator rails are used for decoration purposes, this should be disabled
activatorEjectEnabled: true

# A list of world names where TrainCarts should be disabled
# World names are not case-sensitive
disabledWorlds:
- DefaultWorld1
- DefaultWorld2

# The block materials that can be broken using minecarts
# Players with the admin block break permission can use any type
# Others have to use one from this list
allowedBlockBreakTypes:
- CROPS
- LOG

# Whether or not to show item animations when transferring items
showTransferAnimations: true

# Whether a crafting table must exist when crafting items inside a storage minecart
# When this is set to false and no crafting table is nearby, no item transfer animations are shown
craftingRequireWorkbench: true

# Several shortcuts you can use on announce signs (text is replaced)
messageShortcuts:
  welcome: &eWelcome to &f

# Several shortcuts you can use on switcher and detector signs (text is replaced)
statementShortcuts:
  diamond: i@diamond

# Several shortcuts you can use on signs to set the items
itemShortcuts:
  fuel: ''
  heatable: ''
  armor: gold_boots;iron_helmet;diamond_chestplate;diamond_leggings;gold_leggings;chainmail_chestplate;diamond_helmet;leather_boots;leather_leggings;chainmail_leggings;iron_boots;iron_chestplate;gold_helmet;gold_chestplate;diamond_boots;iron_leggings;leather_helmet;chainmail_boots;leather_chestplate;chainmail_helmet
  sword: wood_sword;stone_sword;iron_sword;gold_sword;iron_sword;diamond_sword
  boots: leather_boots;iron_boots;gold_boots;diamond_boots;chainmail_boots
  leggins: leather_leggings;iron_leggings;gold_leggings;diamond_leggings;chainmail_leggings
  chestplate: leather_chestplate;iron_chestplate;gold_chestplate;diamond_chestplate;chainmail_chestplate
  helmet: leather_helmet;iron_helmet;gold_helmet;diamond_helmet;chainmail_helmet

# Enables parsing signs with (train), as well as [train]
# This makes it easier to write signs with a Mac keyboard layout
parseParentheses: true

